<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Brontide.Reference.Experimental.PersistentInformation</AssemblyName>
    <RootNamespace>Brontide.Reference.Experimental.PersistentInformation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brontide.Reference.Core\Brontide.Reference.Core.csproj" />
  </ItemGroup>
</Project>
